## Radhika
## 20csu267
### September 15, 2022
### Q-Learning

In [1]:
import numpy as np
# r-matrix
r= np.matrix([[-1, -1, -1, -1, 0, -1],
              [-1, -1, -1, 0, -1, 100],
              [-1, -1, -1, 0, -1, -1],
              [-1, 0, 0, -1, 0, -1],
              [-1, 0, 0, -1, -1, 100],
              [-1, 0, -1, -1, 0, 100]])

In [2]:
# q-matrix
q= np.matrix(np.zeros([6, 6]))
q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [11]:
gamma= 0.8
initial_state= 1

In [12]:
# returns all available actions in the state given as an arg
def available_actions(state):
  current_state_row= r[state, ]
  av_act= np.where(current_state_row >= 0)[1]
  return av_act

In [13]:
# get available actions in the current state
available_act= available_actions(initial_state)
available_act

array([3, 5])

In [14]:
# chooses at random which action to be performed with
def sample_next_action(available_actions_range):
  next_action= int(np.random.choice(available_act, 1))
  return next_action

In [18]:
# sample next action to be performed
action= sample_next_action(available_act)
action

5

In [19]:
# updates the q-matrix according to the path selected
def update(current_state, action, gamma):
  max_index= np.where(q[action, ]==np.max(q[action, ]))[1]

  if max_index.shape[0] > 1:
    max_index= int(np.random.choice(max_index, size=1))
  else:
    max_index= int(max_index)
  max_value= q[action, max_index]

  # q-learning formula
  q[current_state, action]= r[current_state, action] + gamma*max_value

#update q-matrix
update(initial_state, action, gamma)

In [20]:
q

matrix([[  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0., 100.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.]])

In [21]:
# training
#train over 10k iterations
for i in range(10000):
  current_state= np.random.randint(0, int(q.shape[0]))
  available_act= available_actions(current_state)
  action= sample_next_action(available_act)
  update(current_state, action, gamma)

In [22]:
q

matrix([[  0.,   0.,   0.,   0., 400.,   0.],
        [  0.,   0.,   0., 320.,   0., 500.],
        [  0.,   0.,   0., 320.,   0.,   0.],
        [  0., 400., 256.,   0., 400.,   0.],
        [  0., 400., 256.,   0.,   0., 500.],
        [  0., 400.,   0.,   0., 400., 500.]])

In [23]:
# normalize the trained q-matrix
print(q/np.max(q)*100)

[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   80.    0. ]
 [  0.   80.   51.2   0.    0.  100. ]
 [  0.   80.    0.    0.   80.  100. ]]


In [24]:
# testing
# goal state= 5

current_state= 1
steps= [current_state]

while current_state != 5:
  next_step_index= np.where(q[current_state, ] == np.max(q[current_state, ]))[1]
  if next_step_index.shape[0] > 1:
    next_step_index= int(np.radom.choice(next_step_index, size= 1))
  else:
    next_step_index= int(next_step_index)

  steps.append(next_step_index)
  current_state= next_step_index

In [25]:
print("Selected path: ", steps)

Selected path:  [1, 5]


In [26]:
q

matrix([[  0.,   0.,   0.,   0., 400.,   0.],
        [  0.,   0.,   0., 320.,   0., 500.],
        [  0.,   0.,   0., 320.,   0.,   0.],
        [  0., 400., 256.,   0., 400.,   0.],
        [  0., 400., 256.,   0.,   0., 500.],
        [  0., 400.,   0.,   0., 400., 500.]])